/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.MedicineCatalog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nidhi Raghavendra
 */
public class CatalogJPanel extends javax.swing.JPanel {

    private Application application;

    /**
     * Creates new form CatalogJPanel
     */
    
    DefaultTableModel medTableModel;
    
    CatalogJPanel(Application application) {
        initComponents();
        
        this.application = application;
        this.medTableModel = (DefaultTableModel) medicineCatalogTable.getModel();
        
        displayMedicineCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicineCatalogTable = new javax.swing.JTable();
        fieldDosage = new javax.swing.JTextField();
        fieldNAme = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicineCatalogTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 64, -1, 340));
        add(fieldDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, 50));

        fieldNAme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNAmeFocusLost(evt);
            }
        });
        fieldNAme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNAmeActionPerformed(evt);
            }
        });
        add(fieldNAme, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 50));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNAmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNAmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNAmeActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        String name = fieldNAme.getText();
        String dosage = fieldDosage.getText();
        // adding medicine
        
        MedicineCatalog catalog = this.application.getCatalog();
                
        catalog.createMedicine(name, Double.valueOf(dosage));
        
        // refrresh table
        displayMedicineCatalog();
    }//GEN-LAST:event_addBtnActionPerformed

    private void fieldNAmeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNAmeFocusLost
        // TODO add your handling code here:
        
        String name = fieldNAme.getText();
        
        Boolean isUnique = this.application.getCatalog().checkIfMedicineUnique(name);
        
        if(isUnique) {
            
        } else {
            fieldNAme.setText("");
            JOptionPane.showMessageDialog(null, "Medicine already exists");
        }
        
    }//GEN-LAST:event_fieldNAmeFocusLost

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        // get the selected row
        
        int selectedRow = medicineCatalogTable.getSelectedRow();
        
        Medicine med = (Medicine) medicineCatalogTable.getValueAt(selectedRow, 0);
            
        this.application.getCatalog().removeMedicine(med.getMedicineName());    
        displayMedicineCatalog();
//        } else {
//            
//        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    public void displayMedicineCatalog() {
        // chekc if the catalog is not empty
        
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        
        if(medicines.size() > 0) {
            // popultate
            
            medTableModel.setRowCount(0);
            
            for(Medicine med: medicines) {
                
                // row[] object for the table
                
                Object row[] = new Object[2];
                row[0] = med;
                row[1] = med.getDosage();
                
                medTableModel.addRow(row);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField fieldDosage;
    private javax.swing.JTextField fieldNAme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicineCatalogTable;
    // End of variables declaration//GEN-END:variables
}
